name: Daily Maintenance

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Clear daily-commit.txt
        run: |
          echo -n '' > daily-commit.txt

      - name: Generate Data and Hash
        run: |
          for x in {1..20}; do
            RND_DATA=$(openssl rand -base64 96)
            TS=$(date +%s%N)
            COMB_DATA="$RND_DATA$TS"
            HSH_VAL=$(echo -n "$COMB_DATA" | sha512sum | awk '{print $1}')

            echo "$RND_DATA" >> daily-commit.txt
            echo "Hash: $HSH_VAL" >> daily-commit.txt
            
            git config --local user.name "Happy-clo"
            git config --local user.email "support@wdsj.one"

            git add daily-commit.txt
            
            git commit -m "chore: Daily maintenance - Iteration $x" || echo "No changes to commit"

            sleep $(( RANDOM % 3 + 1 ))
          done

          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
