name: Daily Maintenance

on:
  push:
  schedule:
    - cron: "0 0 * * *" # 每天午夜只执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Random Data and Complex Hash
        run: |
          for i in {1..5}; do
            RANDOM_DATA=$(openssl rand -base64 96)
            TIMESTAMP=$(date +%s%N)  # 纳秒时间戳
            COMPLEX_DATA="$RANDOM_DATA$TIMESTAMP"  # 组合随机数据和时间戳
            HASH_VALUE=$(echo -n "$COMPLEX_DATA" | sha512sum | awk '{print $1}')  # 使用 SHA-512 算法
            
            echo "$RANDOM_DATA" >> daily-commit.txt
            echo "Hash: $HASH_VALUE" >> daily-commit.txt

            git config --local user.name "Happy-clo"
            git config --local user.email "support@wdsj.one"
            git add daily-commit.txt
            git commit -m "chore: Daily maintenance - $i times" || echo "No changes to commit"
          done

          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
